#! /bin/sh

set -ex

fgrep -q bd3a90dbf573f535c045b76401169abee5e43c19 makedist

build=$(mktemp -d)
trap 'chmod -R u+rwX -- "$build";rm -rf -- "$build"' EXIT

#git archive --remote=$HOME/git/hardhat --prefix=src/ HEAD >$build/balletje
#tar xCf $build $build/balletje
mkdir $build/src
cp -a * $build/src/
echo 'temporarily not available' > $build/src/ChangeLog

(
	set -ex

	cd $build/src

	find /usr/share/libtool -name ltmain.sh -exec cp -v {} . \;
	cp -av /usr/share/common-licenses/GPL-3 COPYING
	cp -av /usr/share/common-licenses/LGPL-3 COPYING.LESSER
	touch NEWS README AUTHORS src/config.h.in

	aclocal
	autoconf
	automake --add-missing
	sh configure

	make -s distcheck

	echo print-archives: >>Makefile
	echo '	@echo $(DIST_ARCHIVES)' >>Makefile
	mkdir $build/archives
	mv $(make -s print-archives) $build/archives/
)

cp -a $build/archives/* .
